name: Docker exist action tester

on: [push]

jobs:
  docker_exist_job:
    runs-on: ubuntu-latest
    name: Docker exist test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker exist action TRUE
        uses: tm-bverret/docker-exist-action@v1.1.2
        id: exist
        with:
          registry: 'docker.io'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: 'hello-world:latest'
      - name: Docker exist action FALSE
        uses: tm-bverret/docker-exist-action@v1.1.2
        id: dont_exist
        with:
          registry: 'docker.io'
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
          image: 'hello-world:fake_tag'
      - name: Get the output TRUE
        run: |
          echo "Value is: ${{ steps.exist.outputs.image_exist }}."
          if (( ${{ steps.exist.outputs.image_exist }} )); then
            exit 0
          else
            exit 1
          fi
      - name: Get the output FALSE
        run: |
          echo "Value is: ${{ steps.dont_exist.outputs.image_exist }}."
          if (( ${{ steps.dont_exist.outputs.image_exist }} )); then
            exit 1
          else
            exit 0
          fi
